graph TD
    A1[Define Objective] --> A2[Define Technical Scope]
    A2 --> A3[Decompose Application]
    A3 --> A4[Analyze Threats]
    A4 --> A5[Vulnerabilities & Weaknesses Analysis]
    A5 --> A6[Model Attacks]
    A6 --> A7[Risk & Impact Analysis]
    A7 --> A1

    style A1 fill:#8ecae6,stroke:#333,stroke-width:1px
    style A2 fill:#219ebc,stroke:#333,stroke-width:1px
    style A3 fill:#ffb703,stroke:#333,stroke-width:1px
    style A4 fill:#fb8500,stroke:#333,stroke-width:1px
    style A5 fill:#e63946,stroke:#333,stroke-width:1px
    style A6 fill:#9d0208,stroke:#fff,stroke-width:1px
    style A7 fill:#6a4c93,stroke:#fff,stroke-width:1px
